repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: file-contents-sorter
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: sort-simple-yaml
      - id: detect-private-key
      - id: forbid-submodules

  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format .
        language: system
        types: [dart]
      - id: dart-analyze
        name: Dart Analyze
        entry: dart analyze
        language: system
        types: [dart]
      - id: import-sorter
        name: Import Sorter
        entry: dart run import_sorter:main
        language: system
        types: [dart]
      - id: check-changelog
        name: Check valid changelog current version
        entry: ./.hooks/check_changelog.sh
        language: system
        types: [dart]
