name: inno_build
description: CLI for building Flutter Windows applications into Windows installer (.exe) using Inno Setup. Automates the installer creation process for easy distribution.
version: 0.3.0
repository: https://github.com/izzalDev/inno_build

environment:
  sdk: ^3.4.4

platforms:
  windows:

dependencies:
  args: ^2.4.2
  cli_spin: ^1.0.1
  path: ^1.9.0
  uuid: ^4.4.2
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  import_sorter: ^4.6.0
