name: Print GitHub Context

on: [push, workflow_dispatch]

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cetak Halo dunia
        id: cetak-halo
        run: echo "Hello World"

      - name: Dump GitHub context
        env:
            GITHUB_CONTEXT: ${{ toJson(steps.cetak-halo) }}
        run: echo "$GITHUB_CONTEXT"
