name: Run Pre-commit Checks and Review Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Dart
      uses: subosito/flutter-action@v2

    - name: Install Dependencies
      run: |
        flutter pub get
        python -m pip install pre-commit

    - name: Run pre-commit hooks
      run: |
        pre-commit install-hooks
        pre-commit run --all-files

    # - name: Run pre-commit hooks
    #   id: pre-commit
    #   run: |
    #     # Run the pre-commit hooks and capture the output and exit code
    #     pre_commit_output=$(pre-commit run --all-files 2>&1)
    #     pre_commit_exit_code=$?

    #     # Save the output and exit code as environment variables
    #     echo "PRE_COMMIT_OUTPUT<<EOF" >> $GITHUB_ENV
    #     echo "$pre_commit_output" >> $GITHUB_ENV
    #     echo "EOF" >> $GITHUB_ENV
    #     echo "PRE_COMMIT_EXIT_CODE=$pre_commit_exit_code" >> $GITHUB_ENV

    - name: Display pre-commit output
      run: |
        echo "Pre-commit output:"
        echo "$PRE_COMMIT_OUTPUT"

    - name: Fail the build if pre-commit hooks failed
      if: ${{ env.PRE_COMMIT_EXIT_CODE != 0 }}
      run: |
        echo "Pre-commit hooks failed with exit code $PRE_COMMIT_EXIT_CODE"
        exit $PRE_COMMIT_EXIT_CODE

    - name: Review Pre-commit Results
      if: failure()
      uses: golfzaptw/action-auto-reviews-from-branches@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_TYPE: REQUEST_CHANGES
        MESSAGE: |
          ## ❌ Pre-commit Hooks Failed

          Some pre-commit hooks have failed. Please fix the following issues before committing:

          ```bash
          [error log file]
          ```

          To automatically fix issues (if possible), run:

          ```bash
          pre-commit run --all-files
          ```

          Ensure that pre-commit is installed and configured in your Git hooks to maintain code consistency. For additional help, please refer to the [CONTRIBUTING.md](https://github.com/izzalDev/inno_build/blob/main/CONTRIBUTING.md) file.
