name: Reformat and Update Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: |
        flutter pub get
        python -m pip install pre-commit

    - name: Run Precommit
      id: pre-commit
      run: |
        pre_commit_output=$(pre-commit run --all-files | tee /dev/tty)
        echo "pre_commit_output=$pre_commit_output" >> $GITHUB_OUTPUT

    - name: Precommit review
      if: failure()
      uses: golfzaptw/action-auto-reviews-from-branches@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        EVENT_TYPE: REQUEST_CHANGES
        BRANCHES: release/*
        AUTHOR: 'pre-commit[bot]'
        MESSAGE: |
          ## ❌ Pre-commit Hooks Failed

          Some pre-commit hooks have failed. Please fix the following issues before committing:

          ```bash
          ${{ steps.pre-commit.outputs.pre_commit_output }}
          ```

          Run the following command to fix issues automatically (if available):

          ```bash
          pre-commit run --all-files
          ```

          Make sure that pre-commit is installed and set up in your Git hooks to help ensure code consistency. If you need further assistance, please refer to the CONTRIBUTING.md file.
