name: Reformat and Update Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dart
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: |
        flutter pub get
        python -m pip install pre-commit

    - name: Run Precommit
      run: printf "$(pre-commit run --all-files)"

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
