name: pre-commit

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          echo ${{ github.event.pull_request.head.repo.full_name }}
          echo ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter pub get
      - uses: pre-commit/action@v3.0.1
        id: precommit
      - uses: EndBug/add-and-commit@v9
        if: steps.precommit == 'failure'
        id: commit_changes
        with:
          message: \[pre-commit\] auto update

      - name: Review Pre-commit Results
        if: steps.commit_changes.conclusion == 'failure'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: .github/pre_commit_failed.md
          reactions: eyes
