name: Reformat and Update Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: |
        flutter pub get
        python -m pip install pre-commit

    - name: Run Precommit
      id: pre-commit
      run: |
        pre_commit_output=$(pre-commit run --all-files)
        echo "pre_commit_output=$pre_commit_output" >> "$GITHUB_OUTPUT"
        echo $pre_commit_output

    - name: Precommit review
      if: failure()
      uses: golfzaptw/action-auto-reviews-from-branches@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        EVENT_TYPE: REQUEST_CHANGES
        MESSAGE: |
          ## ❌ Pre-commit Hooks Failed

          Some pre-commit hooks have failed. Please fix the following issues before committing:

          ```bash
          ${{ steps.pre-commit.outputs.pre_commit_output }}
          ```

          Run the following command to fix issues automatically (if available) and reproduce output shown above, run:

          ```bash
          pre-commit run --all-files
          ```

          Ensure that pre-commit is installed and configured in your Git hooks to maintain code consistency. For additional help, please refer to the [CONTRIBUTING.md](https://github.com/izzalDev/inno_build/blob/main/CONTRIBUTE.md) file.
