name: Run Pre-commit Checks and Review Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Dart
      uses: subosito/flutter-action@v2

    - name: Install Dependencies
      run: |
        flutter pub get
        python -m pip install pre-commit

    - name: Run Pre-commit Hooks
      id: pre-commit
      run: |
        pre_commit_output=$(pre-commit run --all-files)
        echo "$pre_commit_output"  # Print output to the console
        echo "PRE_COMMIT_OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$pre_commit_output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Review Pre-commit Results
      if: failure()
      uses: golfzaptw/action-auto-reviews-from-branches@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_TYPE: REQUEST_CHANGES
        MESSAGE: |
          ## ❌ Pre-commit Hooks Failed

          Some pre-commit hooks have failed. Please fix the following issues before committing:

          ```bash
          ${{ env.PRE_COMMIT_OUTPUT }}
          ```

          To automatically fix issues (if possible), run:

          ```bash
          pre-commit run --all-files
          ```

          Ensure that pre-commit is installed and configured in your Git hooks to maintain code consistency. For additional help, please refer to the [CONTRIBUTING.md](https://github.com/izzalDev/inno_build/blob/main/CONTRIBUTING.md) file.
