name: Reformat and Update Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dart
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: flutter pub get

    - uses: pre-commit/action@v3.0.1
      with:
        args: --all-files

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit changes
      if: steps.git-check.outputs.changes == 'Changes detected'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m 'Automated code reformat'
        git push
