name: Pre-commit Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run Pre-commit and Check for Failures
      run: |
        pre-commit run --all-files | tee pre_commit_output.txt
        if grep -q "Failed" pre_commit_output.txt; then
          echo "Pre-commit checks failed. Exiting..."
          exit 1
        fi

    - name: Generate Pre-commit Report
      if: failure()
      run: |
        sed '/<pre_commit_output>/r pre_commit_output.log' .github/pre-commit.md \
        | sed '/<pre_commit_output>/d' \
        > pre-commit.md
        cat pre-commit.md

    - name: Review Pre-commit Results
      if: failure()
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: pre-commit.md
        reactions: heart
