name: pre-commit

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter pub get
      - uses: pre-commit/action@v3.0.1
      - name: Review Pre-commit Results
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: .github/pre-commit.md
          reactions: eyes
