name: Reformat and Update Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  reformat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dart
      uses: subosito/flutter-action@v2

    - name: Install dependencies
      run: |
        flutter pub get
        python -m pip install pre-commit

    - name: Run Precommit
      run: |
        pre_commit_output=$(pre-commit run --all-files 2>&1)

    - name: Precommit review
      if: failure()
      uses: golfzaptw/action-auto-reviews-from-branches@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        EVENT_TYPE: REQUEST_CHANGES
        BRANCHES: release/*
        AUTHOR: 'github-action[bot]'
        MESSAGE: |
          ## ❌ Pre-commit Hooks Failed

          Some pre-commit hooks have failed. Please fix the following issues before committing:

          ```bash

          ```

          Run the following command to fix issues automatically (if available):

          ```bash
          pre-commit run --all-files


