name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: example

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [release, debug]
        options: 
          - ""
          - "--app-id"
          - "--install"
          - "--app-id --install"
        verbose: [ "--verbose", "--quiet"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.3

      - name: Install dependencies
        run: flutter pub get

      - name: Run inno_build with Matrix Configuration
        run: |
          dart run inno_build --${{ matrix.mode }} ${{ matrix.options }} ${{ matrix.verbose }}
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Expected exit code 0, but got $EXIT_CODE. Stopping execution."
            exit 1
          fi

      - name: Upload Installer Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: "example/build/windows/x64/installer/Release/Output/mysetup.exe"
